# 项目环境配置
profile-env: ${profile-env}

# apollo
app:
  id: ${project.name}

apollo:
  env: pro
  meta: http://apollo-configservice-pro.riverstar.cn:18080
  bootstrap:
    enabled: true
    namespaces: application.yml